### ISSUE TITLE
关于同时出现两个或以上的通配符的bug

### ISSUE THREAD

**Issue by sorvon** [MisterChangRay/1024RegisterTool#2]
我仔细看了一下，bug应该在MainForm.cs文件第210~220行调用的Replace函数。
c#中String的Replace只能全部替换，这样第一次执行的时候就把所有的通配符(比如{c})全部替换成了a，第二次则全部替换成了b。
c#要实现只替换一次的效果好像必须要借助Regex的Replace函数，它的第三个参数传入的数字就是最大的替换次数。

唉，想上个岸不容易。

**Comment by MisterChangRay** [comment]
上岸了吗老铁
另外感谢bug修复, 社区需要你这种人才

**Comment by sorvon** [comment]
没呢，学生党(学软件)，抢码太难，尝试上GitHub找点科技，就看到了这个项目，用的时候发现了这个bug，本着挑战自己的想法尝试着修复了一下，没想到成功了。（其实编程尝试所有可能的码我之前也想过，但没想到直接使用post可以绕过验证码！）
