### ISSUE TITLE
字母只能试到"f"，是故意这么做的吗？

### ISSUE THREAD

**Issue by falltoearth** [MisterChangRay/1024RegisterTool#7]
字母只能试到"f"，是故意这么做的吗？

''''不知道2022年这个还能不能用，感谢楼主

**Comment by MisterChangRay** [comment]
所有的邀请码都是 16进制的啊， 当然只有 0 - f啊老哥

**Comment by falltoearth** [comment]
学习了，多谢。

如果方便的话能不能帮忙测试一下现在软件的可用性？我试了多个组合都没有成功（当然也可能是码有问题），会不会有可能是现在接口变了导致软件失效？

**Comment by MisterChangRay** [comment]
测试了下, 可以使用的。  
使用软件不代表100% 成功， 软件仅仅是加快了尝试的速度而已。也有可能码被别人先尝试出来。

**Comment by falltoearth** [comment]
> 测试了下, 可以使用的。 使用软件不代表100% 成功， 软件仅仅是加快了尝试的速度而已。也有可能码被别人先尝试出来。

感谢，已成功上岸。虽然不是软件直接试出来的，但也帮忙排除了无效选项。
