### ISSUE TITLE
现在草榴加上了验证码机制，你这个估计不好用了

### ISSUE THREAD

**Issue by zongxiaomi** [MisterChangRay/1024RegisterTool#8]
<img width="687" alt="image" src="https://user-images.githubusercontent.com/14845843/187059678-df7cfe47-8bff-40ad-b7e2-2c1285aab382.png">

**Comment by MisterChangRay** [comment]
现在有验证码了吗？  验证码是那种？

**Comment by zongxiaomi** [comment]
<img width="745" alt="image" src="https://user-images.githubusercontent.com/14845843/188952045-633d9ac0-bb29-4feb-b960-ee7b119344c0.png">
 
像这种，做的时候没有这个吗

**Comment by MisterChangRay** [comment]
之前是没有这个的，估计也是这两年才加上

**Comment by sayusok** [comment]
提示：请求被中止: 未能创建 SSL/TLS 安全通道。

是不能用了，还是我自己的问题？

**Comment by MisterChangRay** [comment]
V1.1.0 已经发布，可以正常使用了。
