### ISSUE TITLE
好像不能用了

### ISSUE THREAD

**Issue by EnormousKnob** [MisterChangRay/1024RegisterTool#9]
2022/12/3 12:57:51: 网络异常,请检查网络状况:请求被中止: 未能创建 SSL/TLS 安全通道。
2022/12/3 12:57:51: 本次任务结束
--------------------
一直在循环

**Comment by EnormousKnob** [comment]
页面可以正常打开，整个子网都是国际环境，只有这个exe是这样的提示

**Comment by MisterChangRay** [comment]
V1.1.0 已经发布，可以正常使用了。
